[package]
name = "task01"
version = "0.1.0"
authors = ["Luis Sanchez <luis.sanchez@bisimulations.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "task01"
path = "main.rs"
